### ISSUE TITLE
Do NOT install in 2019 versions

### ISSUE THREAD

**Issue by contika** [spatie/phpstorm-blade-x#2]
It will crash PHPStorm

**Comment by brendt** [comment]
I'm using it in PhpStorm 2019.1, all looks fine?

**Comment by contika** [comment]
Well, then you must have installed it on an older version and upgraded your PHPStorm. If I now install it on 2019 version I get errors and PHPStorm does not start without removing the plugin

**Comment by brendt** [comment]
My bad, I was thinking this was our blade-x package while it is our plugin. This plugin isn't done yet, so that's why it doesn't work.
